### PR TITLE
Centos7

### PR DESCRIPTION
**Pull request by aliouba**
On Centos VMs, we need to use ["sginfo", "-s", device]  to get the serial ID.

### CODE REVIEW

**Comment by aliouba** [comment]
Hello Jose Manuel,

It's done, I check the OS and run  ["sginfo", "-s", device] for Centos vms.

Thakns!

**Comment by aliouba** [comment]
Hello Jose,

You're right. It's fixed. 

Many Thanks!

**Comment by mitch-hulscher** [comment]
Any chance this PR is getting merged anytime soon?

**Comment by pratikvgupta** [comment]
Thanks for the fix!

**Pull request merged**
